name: Purge jsDelivr CDN (Main Only)

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

jobs:
  purge-all:
    runs-on: ubuntu-latest
    steps:
      - name: Purge all CDN URLs
        run: |
          declare -a CDN_URLS=(
            "https://purge.jsdelivr.net/gh/Black-Ink-Technologies/bit-age-app-scripts@1.x.x/script.develop.min.js"
            "https://purge.jsdelivr.net/gh/Black-Ink-Technologies/bit-age-app-scripts@1.x.x/script.staging.min.js"
            "https://purge.jsdelivr.net/gh/Black-Ink-Technologies/bit-age-app-scripts@1.x.x/script.min.js"
          )

          for url in "${CDN_URLS[@]}"; do
            echo "Purging CDN: $url"
            RESPONSE=$(curl -X GET "$url")
            echo "Response: $RESPONSE"
          done
